openapi: '3.0.2'

info:
  title: mikrocms swagger
  version: '1.0.0'
  contact:
    name: Musa Sutisna
    email: mus4.sutisn4@gmail.com

servers:
  - url: http://localhost:3000/swagger
    description: Development Server

paths:
  /:
    get:
      tags:
        - swagger
      description: 'Swagger UI page'
      produces:
        - text/html
      responses:
        '200':
          description: 'A successful response displaying the Swagger UI page.'
          schema:
            type: string
    post:
      tags:
        - swagger
      description: 'Process authentication for login'
      produces:
        - text/html
      requestBody:
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
              required:
                - username
                - password
      responses:
        '200':
          description: 'A successful response displaying the Swagger UI page.'
          schema:
            type: string
  